version: "3.9"
services:
  db1:
    container_name: db1
    image: postgres:14.5
    environment:
      POSTGRES_DB: "PSHENITSYN_204"
      POSTGRES_USER: "PSHENITSYN_204"
      POSTGRES_PASSWORD: "PSHENITSYN_204"
      PGDATA: "/var/lib/postgresql/data/pgdata-db1"
    volumes:
      - ./docker/db/scripts/create_library.sql:/docker-entrypoint-initdb.d/create_library.sql
      - ./dz:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db2:
    container_name: db2
    image: postgres:14.5
    environment:
      POSTGRES_DB: "PSHENITSYN_204"
      POSTGRES_USER: "PSHENITSYN_204"
      POSTGRES_PASSWORD: "PSHENITSYN_204"
      PGDATA: "/var/lib/postgresql/data/pgdata-db2"
    volumes:
      - ./docker/db/scripts/create_station.sql:/docker-entrypoint-initdb.d/create_station.sql
      - ./dz:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db3:
    container_name: db3
    image: postgres:14.5
    environment:
      POSTGRES_DB: "PSHENITSYN_204"
      POSTGRES_USER: "PSHENITSYN_204"
      POSTGRES_PASSWORD: "PSHENITSYN_204"
      PGDATA: "/var/lib/postgresql/data/pgdata-db3"
    volumes:
      - ./docker/db/scripts/create_station_hospital.sql:/docker-entrypoint-initdb.d/create_station_hospital.sql
      - ./dz:/var/lib/postgresql/data
    ports:
      - "5432:5432"
